### ISSUE TITLE
Containerize the app and test on OpenShift

### ISSUE THREAD

**Issue by husky-parul** [CS6620-S21/Asynchronous-quantum-job-submission-framework#7]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Containerize the app and test on OpenShift

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by saisankargochhayat** [comment]
- [ ] Containerize the API and the Cron-job
- [ ] Create secret templates and `oc create secrets`
- [ ] Create a template for always running API (reading secrets and pulling container from registry)
- [ ] Create a template for cronjob (reading secrets and pulling container from registry)
- [ ] Test workings
